export const consoleNavEntries = [
  { to: "/", label: "Dashboard", iconKey: "dashboard" },
  { to: "/agents", label: "智能体", iconKey: "bot" },
  { to: "/teams", label: "团队", iconKey: "network" },
  { to: "/runs", label: "运行历史", iconKey: "runs" },
  { to: "/subagents", label: "子代理", iconKey: "bot" },
  { to: "/subagent-specialists", label: "专家库", iconKey: "brainCircuit" },
  { to: "/subagent-marketplace", label: "专家市场", iconKey: "store" },
  { to: "/sandboxes", label: "沙箱", iconKey: "box" },
  { to: "/tools", label: "工具", iconKey: "tools" },
  { to: "/tools/config", label: "工具配置", iconKey: "settings" },
  { to: "/knowledge", label: "知识库", iconKey: "knowledge" },
  { to: "/observability", label: "观测", iconKey: "activity" },
  { to: "/token-savings", label: "标记节省", iconKey: "gauge" },
  { to: "/evals", label: "评测", iconKey: "evals" },
  { to: "/settings/policies", label: "策略", iconKey: "shield" },
  { to: "/settings/models", label: "模型", iconKey: "brain" },
  { to: "/settings/secrets", label: "密钥库", iconKey: "key" },
  { to: "/settings/users", label: "用户", iconKey: "users" },
  { to: "/settings/api-keys", label: "API Keys", iconKey: "key" },
  { to: "/settings/audit", label: "审计", iconKey: "audit" },
  { to: "/settings/data-management", label: "数据", iconKey: "database" },
  { to: "/help", label: "帮助", iconKey: "help" },
] as const;
