from typing import Literal

from pydantic import BaseModel, Field

RiskLevel = Literal["low", "medium", "high", "critical"]


class ToolMetadata(BaseModel):
    name: str
    description: str
    category: str
    source: Literal["builtin", "mcp"] = "builtin"
    risk_level: RiskLevel
    requires_sandbox: bool
    network_policy: str = "none"
    timeout_seconds: int = Field(default=60, ge=1)
    allowed_roles: list[str] = Field(default_factory=lambda: ["admin", "engineer"])
    audit_level: str = "standard"
    idempotent: bool = True
    input_schema: dict = Field(default_factory=dict)
    mcp_server: str | None = None
    mcp_method: str | None = None


class ToolRegistry(BaseModel):
    tools: dict[str, ToolMetadata]

    @classmethod
    def default(cls) -> "ToolRegistry":
        tools = [
            ToolMetadata(
                name="read_file",
                description="读取工作区文件。",
                category="filesystem",
                risk_level="low",
                requires_sandbox=False,
                network_policy="none",
                timeout_seconds=10,
                audit_level="standard",
                idempotent=True,
            ),
            ToolMetadata(
                name="list_files",
                description="列出工作区文件。",
                category="filesystem",
                risk_level="low",
                requires_sandbox=False,
                network_policy="none",
                timeout_seconds=10,
                audit_level="standard",
                idempotent=True,
            ),
            ToolMetadata(
                name="write_file",
                description="在任务工作区写入任务产物。",
                category="filesystem",
                risk_level="high",
                requires_sandbox=True,
                network_policy="none",
                timeout_seconds=30,
                audit_level="elevated",
                idempotent=False,
            ),
            ToolMetadata(
                name="run_shell",
                description="在 Docker 沙箱内运行 Shell 命令。",
                category="shell",
                risk_level="high",
                requires_sandbox=True,
                network_policy="none",
                timeout_seconds=60,
                audit_level="elevated",
                idempotent=False,
            ),
            ToolMetadata(
                name="run_tests",
                description="在 Docker 沙箱内运行测试。",
                category="shell",
                risk_level="high",
                requires_sandbox=True,
                network_policy="none",
                timeout_seconds=300,
                audit_level="elevated",
                idempotent=True,
            ),
            ToolMetadata(
                name="network_request",
                description="在 Docker 沙箱内执行受控网络请求。",
                category="network",
                risk_level="high",
                requires_sandbox=True,
                network_policy="restricted",
                timeout_seconds=30,
                allowed_roles=["admin"],
                audit_level="critical",
                idempotent=False,
            ),
            ToolMetadata(
                name="git_command",
                description="在 Docker 沙箱内运行 Git 命令。",
                category="git",
                risk_level="high",
                requires_sandbox=True,
                network_policy="restricted",
                timeout_seconds=120,
                audit_level="elevated",
                idempotent=False,
            ),
            ToolMetadata(
                name="mcp_context_search",
                description="通过 MCP Adapter 查询外部上下文。",
                category="mcp",
                source="mcp",
                risk_level="low",
                requires_sandbox=False,
                network_policy="restricted",
                timeout_seconds=30,
                audit_level="standard",
                idempotent=True,
                input_schema={
                    "type": "object",
                    "properties": {
                        "query": {"type": "string"},
                        "limit": {"type": "integer", "default": 5},
                    },
                    "required": ["query"],
                },
                mcp_server="local-context",
                mcp_method="context.search",
            ),
            ToolMetadata(
                name="mcp_artifact_put",
                description="通过 MCP Adapter 写入任务 Artifact 记录。",
                category="mcp",
                source="mcp",
                risk_level="medium",
                requires_sandbox=False,
                network_policy="none",
                timeout_seconds=30,
                audit_level="elevated",
                idempotent=False,
                input_schema={
                    "type": "object",
                    "properties": {
                        "name": {"type": "string"},
                        "content": {"type": "string"},
                    },
                    "required": ["name", "content"],
                },
                mcp_server="local-artifacts",
                mcp_method="artifact.put",
            ),
            ToolMetadata(
                name="github.list_issues",
                description="列出 GitHub 仓库 Issue。",
                category="mcp",
                source="mcp",
                risk_level="low",
                requires_sandbox=False,
                network_policy="restricted",
                timeout_seconds=30,
                audit_level="standard",
                idempotent=True,
                input_schema={
                    "type": "object",
                    "properties": {
                        "repo": {"type": "string"},
                        "state": {"type": "string", "default": "open"},
                        "labels": {"type": "string"},
                        "limit": {"type": "integer", "default": 20},
                    },
                    "required": ["repo"],
                },
                mcp_server="github",
                mcp_method="list_issues",
            ),
            ToolMetadata(
                name="github.get_issue",
                description="读取 GitHub Issue 详情和评论。",
                category="mcp",
                source="mcp",
                risk_level="low",
                requires_sandbox=False,
                network_policy="restricted",
                timeout_seconds=30,
                audit_level="standard",
                idempotent=True,
                input_schema={
                    "type": "object",
                    "properties": {
                        "repo": {"type": "string"},
                        "number": {"type": "integer"},
                        "include_comments": {"type": "boolean", "default": False},
                    },
                    "required": ["repo", "number"],
                },
                mcp_server="github",
                mcp_method="get_issue",
            ),
            ToolMetadata(
                name="github.list_pulls",
                description="列出 GitHub Pull Request。",
                category="mcp",
                source="mcp",
                risk_level="low",
                requires_sandbox=False,
                network_policy="restricted",
                timeout_seconds=30,
                audit_level="standard",
                idempotent=True,
                input_schema={
                    "type": "object",
                    "properties": {
                        "repo": {"type": "string"},
                        "state": {"type": "string", "default": "open"},
                        "limit": {"type": "integer", "default": 20},
                    },
                    "required": ["repo"],
                },
                mcp_server="github",
                mcp_method="list_pulls",
            ),
            ToolMetadata(
                name="github.get_pull",
                description="读取 GitHub Pull Request 详情和文件变更。",
                category="mcp",
                source="mcp",
                risk_level="low",
                requires_sandbox=False,
                network_policy="restricted",
                timeout_seconds=30,
                audit_level="standard",
                idempotent=True,
                input_schema={
                    "type": "object",
                    "properties": {
                        "repo": {"type": "string"},
                        "number": {"type": "integer"},
                    },
                    "required": ["repo", "number"],
                },
                mcp_server="github",
                mcp_method="get_pull",
            ),
            ToolMetadata(
                name="github.search_code",
                description="通过 GitHub Search API 搜索代码。",
                category="mcp",
                source="mcp",
                risk_level="low",
                requires_sandbox=False,
                network_policy="restricted",
                timeout_seconds=30,
                audit_level="standard",
                idempotent=True,
                input_schema={
                    "type": "object",
                    "properties": {
                        "query": {"type": "string"},
                        "repo": {"type": "string"},
                        "language": {"type": "string"},
                        "limit": {"type": "integer", "default": 20},
                    },
                    "required": ["query"],
                },
                mcp_server="github",
                mcp_method="search_code",
            ),
            ToolMetadata(
                name="slack.search_messages",
                description="搜索 Slack 消息。",
                category="mcp",
                source="mcp",
                risk_level="low",
                requires_sandbox=False,
                network_policy="restricted",
                timeout_seconds=30,
                audit_level="standard",
                idempotent=True,
                input_schema={
                    "type": "object",
                    "properties": {
                        "query": {"type": "string"},
                        "channel": {"type": "string"},
                        "user": {"type": "string"},
                        "limit": {"type": "integer", "default": 20},
                    },
                    "required": ["query"],
                },
                mcp_server="slack",
                mcp_method="search_messages",
            ),
            ToolMetadata(
                name="slack.list_channels",
                description="列出 Slack 频道。",
                category="mcp",
                source="mcp",
                risk_level="low",
                requires_sandbox=False,
                network_policy="restricted",
                timeout_seconds=30,
                audit_level="standard",
                idempotent=True,
                input_schema={
                    "type": "object",
                    "properties": {
                        "types": {"type": "string"},
                        "limit": {"type": "integer", "default": 100},
                    },
                },
                mcp_server="slack",
                mcp_method="list_channels",
            ),
            ToolMetadata(
                name="slack.get_thread",
                description="读取 Slack thread 和回复。",
                category="mcp",
                source="mcp",
                risk_level="low",
                requires_sandbox=False,
                network_policy="restricted",
                timeout_seconds=30,
                audit_level="standard",
                idempotent=True,
                input_schema={
                    "type": "object",
                    "properties": {
                        "channel": {"type": "string"},
                        "thread_ts": {"type": "string"},
                    },
                    "required": ["channel", "thread_ts"],
                },
                mcp_server="slack",
                mcp_method="get_thread",
            ),
            ToolMetadata(
                name="sandbox.read_file",
                description="读取沙箱工作区内文件。",
                category="mcp",
                source="mcp",
                risk_level="medium",
                requires_sandbox=True,
                network_policy="none",
                timeout_seconds=10,
                audit_level="elevated",
                idempotent=True,
                input_schema={
                    "type": "object",
                    "properties": {
                        "path": {"type": "string"},
                        "max_bytes": {"type": "integer", "default": 1000000},
                    },
                    "required": ["path"],
                },
                mcp_server="sandbox",
                mcp_method="read_file",
            ),
            ToolMetadata(
                name="sandbox.list_files",
                description="列出沙箱工作区内目录。",
                category="mcp",
                source="mcp",
                risk_level="medium",
                requires_sandbox=True,
                network_policy="none",
                timeout_seconds=10,
                audit_level="elevated",
                idempotent=True,
                input_schema={
                    "type": "object",
                    "properties": {
                        "path": {"type": "string", "default": "."},
                        "pattern": {"type": "string", "default": "*"},
                        "max_entries": {"type": "integer", "default": 200},
                    },
                },
                mcp_server="sandbox",
                mcp_method="list_files",
            ),
            ToolMetadata(
                name="sandbox.write_file",
                description="写入沙箱工作区内文件。",
                category="mcp",
                source="mcp",
                risk_level="high",
                requires_sandbox=True,
                network_policy="none",
                timeout_seconds=30,
                audit_level="critical",
                idempotent=False,
                input_schema={
                    "type": "object",
                    "properties": {
                        "path": {"type": "string"},
                        "content": {"type": "string"},
                        "encoding": {"type": "string", "default": "utf-8"},
                    },
                    "required": ["path", "content"],
                },
                mcp_server="sandbox",
                mcp_method="write_file",
            ),
            ToolMetadata(
                name="sandbox.delete_file",
                description="删除沙箱工作区内文件。",
                category="mcp",
                source="mcp",
                risk_level="high",
                requires_sandbox=True,
                network_policy="none",
                timeout_seconds=30,
                audit_level="critical",
                idempotent=False,
                input_schema={
                    "type": "object",
                    "properties": {"path": {"type": "string"}},
                    "required": ["path"],
                },
                mcp_server="sandbox",
                mcp_method="delete_file",
            ),
        ]
        return cls(tools={tool.name: tool for tool in tools})

    def list_tools(self) -> list[ToolMetadata]:
        return list(self.tools.values())
