from typing import Literal

from pydantic import BaseModel, Field

RiskLevel = Literal["low", "medium", "high", "critical"]


class ToolMetadata(BaseModel):
    name: str
    description: str
    category: str
    source: Literal["builtin", "mcp"] = "builtin"
    risk_level: RiskLevel
    requires_sandbox: bool
    network_policy: str = "none"
    timeout_seconds: int = Field(default=60, ge=1)
    allowed_roles: list[str] = Field(default_factory=lambda: ["admin", "engineer"])
    audit_level: str = "standard"
    idempotent: bool = True
    input_schema: dict = Field(default_factory=dict)
    mcp_server: str | None = None
    mcp_method: str | None = None


class ToolRegistry(BaseModel):
    tools: dict[str, ToolMetadata]

    @classmethod
    def default(cls) -> "ToolRegistry":
        tools = [
            ToolMetadata(
                name="read_file",
                description="读取工作区文件。",
                category="filesystem",
                risk_level="low",
                requires_sandbox=False,
                network_policy="none",
                timeout_seconds=10,
                audit_level="standard",
                idempotent=True,
            ),
            ToolMetadata(
                name="list_files",
                description="列出工作区文件。",
                category="filesystem",
                risk_level="low",
                requires_sandbox=False,
                network_policy="none",
                timeout_seconds=10,
                audit_level="standard",
                idempotent=True,
            ),
            ToolMetadata(
                name="write_file",
                description="在任务工作区写入任务产物。",
                category="filesystem",
                risk_level="high",
                requires_sandbox=True,
                network_policy="none",
                timeout_seconds=30,
                audit_level="elevated",
                idempotent=False,
            ),
            ToolMetadata(
                name="run_shell",
                description="在 Docker 沙箱内运行 Shell 命令。",
                category="shell",
                risk_level="high",
                requires_sandbox=True,
                network_policy="none",
                timeout_seconds=60,
                audit_level="elevated",
                idempotent=False,
            ),
            ToolMetadata(
                name="run_tests",
                description="在 Docker 沙箱内运行测试。",
                category="shell",
                risk_level="high",
                requires_sandbox=True,
                network_policy="none",
                timeout_seconds=300,
                audit_level="elevated",
                idempotent=True,
            ),
            ToolMetadata(
                name="network_request",
                description="在 Docker 沙箱内执行受控网络请求。",
                category="network",
                risk_level="high",
                requires_sandbox=True,
                network_policy="restricted",
                timeout_seconds=30,
                allowed_roles=["admin"],
                audit_level="critical",
                idempotent=False,
            ),
            ToolMetadata(
                name="git_command",
                description="在 Docker 沙箱内运行 Git 命令。",
                category="git",
                risk_level="high",
                requires_sandbox=True,
                network_policy="restricted",
                timeout_seconds=120,
                audit_level="elevated",
                idempotent=False,
            ),
            ToolMetadata(
                name="mcp_context_search",
                description="通过 MCP Adapter 查询外部上下文。",
                category="mcp",
                source="mcp",
                risk_level="low",
                requires_sandbox=False,
                network_policy="restricted",
                timeout_seconds=30,
                audit_level="standard",
                idempotent=True,
                input_schema={
                    "type": "object",
                    "properties": {
                        "query": {"type": "string"},
                        "limit": {"type": "integer", "default": 5},
                    },
                    "required": ["query"],
                },
                mcp_server="local-context",
                mcp_method="context.search",
            ),
            ToolMetadata(
                name="mcp_artifact_put",
                description="通过 MCP Adapter 写入任务 Artifact 记录。",
                category="mcp",
                source="mcp",
                risk_level="low",
                requires_sandbox=False,
                network_policy="none",
                timeout_seconds=30,
                audit_level="critical",
                idempotent=False,
                input_schema={
                    "type": "object",
                    "properties": {
                        "name": {"type": "string"},
                        "content": {"type": "string"},
                        "idempotency_key": {"type": "string"},
                    },
                    "required": ["name", "content", "idempotency_key"],
                },
                mcp_server="local-artifacts",
                mcp_method="artifact.put",
            ),
            ToolMetadata(
                name="github.list_issues",
                description="列出 GitHub 仓库 Issue。",
                category="mcp",
                source="mcp",
                risk_level="low",
                requires_sandbox=False,
                network_policy="restricted",
                timeout_seconds=30,
                audit_level="standard",
                idempotent=True,
                input_schema={
                    "type": "object",
                    "properties": {
                        "repo": {"type": "string"},
                        "state": {"type": "string", "default": "open"},
                        "labels": {"type": "string"},
                        "limit": {"type": "integer", "default": 20},
                    },
                    "required": ["repo"],
                },
                mcp_server="github",
                mcp_method="list_issues",
            ),
            ToolMetadata(
                name="github.get_issue",
                description="读取 GitHub Issue 详情和评论。",
                category="mcp",
                source="mcp",
                risk_level="low",
                requires_sandbox=False,
                network_policy="restricted",
                timeout_seconds=30,
                audit_level="standard",
                idempotent=True,
                input_schema={
                    "type": "object",
                    "properties": {
                        "repo": {"type": "string"},
                        "number": {"type": "integer"},
                        "include_comments": {"type": "boolean", "default": False},
                    },
                    "required": ["repo", "number"],
                },
                mcp_server="github",
                mcp_method="get_issue",
            ),
            ToolMetadata(
                name="github.list_pulls",
                description="列出 GitHub Pull Request。",
                category="mcp",
                source="mcp",
                risk_level="low",
                requires_sandbox=False,
                network_policy="restricted",
                timeout_seconds=30,
                audit_level="standard",
                idempotent=True,
                input_schema={
                    "type": "object",
                    "properties": {
                        "repo": {"type": "string"},
                        "state": {"type": "string", "default": "open"},
                        "limit": {"type": "integer", "default": 20},
                    },
                    "required": ["repo"],
                },
                mcp_server="github",
                mcp_method="list_pulls",
            ),
            ToolMetadata(
                name="github.get_pull",
                description="读取 GitHub Pull Request 详情和文件变更。",
                category="mcp",
                source="mcp",
                risk_level="low",
                requires_sandbox=False,
                network_policy="restricted",
                timeout_seconds=30,
                audit_level="standard",
                idempotent=True,
                input_schema={
                    "type": "object",
                    "properties": {
                        "repo": {"type": "string"},
                        "number": {"type": "integer"},
                    },
                    "required": ["repo", "number"],
                },
                mcp_server="github",
                mcp_method="get_pull",
            ),
            ToolMetadata(
                name="github.search_code",
                description="通过 GitHub Search API 搜索代码。",
                category="mcp",
                source="mcp",
                risk_level="low",
                requires_sandbox=False,
                network_policy="restricted",
                timeout_seconds=30,
                audit_level="standard",
                idempotent=True,
                input_schema={
                    "type": "object",
                    "properties": {
                        "query": {"type": "string"},
                        "repo": {"type": "string"},
                        "language": {"type": "string"},
                        "limit": {"type": "integer", "default": 20},
                    },
                    "required": ["query"],
                },
                mcp_server="github",
                mcp_method="search_code",
            ),
            ToolMetadata(
                name="github.create_issue_comment",
                description="在 GitHub Issue 或 Pull Request 下创建评论。",
                category="mcp",
                source="mcp",
                risk_level="high",
                requires_sandbox=False,
                network_policy="restricted",
                timeout_seconds=30,
                audit_level="critical",
                idempotent=False,
                input_schema={
                    "type": "object",
                    "properties": {
                        "repo": {"type": "string"},
                        "number": {"type": "integer"},
                        "body": {"type": "string"},
                        "idempotency_key": {"type": "string"},
                    },
                    "required": ["repo", "number", "body", "idempotency_key"],
                },
                mcp_server="github",
                mcp_method="create_issue_comment",
            ),
            ToolMetadata(
                name="github.create_issue",
                description="创建 GitHub Issue。",
                category="mcp",
                source="mcp",
                risk_level="high",
                requires_sandbox=False,
                network_policy="restricted",
                timeout_seconds=30,
                audit_level="critical",
                idempotent=False,
                input_schema={
                    "type": "object",
                    "properties": {
                        "repo": {"type": "string"},
                        "title": {"type": "string"},
                        "body": {"type": "string"},
                        "labels": {"type": "array", "items": {"type": "string"}},
                        "assignees": {"type": "array", "items": {"type": "string"}},
                        "idempotency_key": {"type": "string"},
                    },
                    "required": ["repo", "title", "idempotency_key"],
                },
                mcp_server="github",
                mcp_method="create_issue",
            ),
            ToolMetadata(
                name="github.create_pull_review",
                description="创建 GitHub Pull Request Review。",
                category="mcp",
                source="mcp",
                risk_level="high",
                requires_sandbox=False,
                network_policy="restricted",
                timeout_seconds=30,
                audit_level="critical",
                idempotent=False,
                input_schema={
                    "type": "object",
                    "properties": {
                        "repo": {"type": "string"},
                        "number": {"type": "integer"},
                        "body": {"type": "string"},
                        "event": {
                            "type": "string",
                            "enum": ["APPROVE", "REQUEST_CHANGES", "COMMENT"],
                        },
                        "idempotency_key": {"type": "string"},
                    },
                    "required": ["repo", "number", "event", "idempotency_key"],
                },
                mcp_server="github",
                mcp_method="create_pull_review",
            ),
            ToolMetadata(
                name="slack.search_messages",
                description="搜索 Slack 消息。",
                category="mcp",
                source="mcp",
                risk_level="low",
                requires_sandbox=False,
                network_policy="restricted",
                timeout_seconds=30,
                audit_level="standard",
                idempotent=True,
                input_schema={
                    "type": "object",
                    "properties": {
                        "query": {"type": "string"},
                        "channel": {"type": "string"},
                        "user": {"type": "string"},
                        "limit": {"type": "integer", "default": 20},
                    },
                    "required": ["query"],
                },
                mcp_server="slack",
                mcp_method="search_messages",
            ),
            ToolMetadata(
                name="slack.list_channels",
                description="列出 Slack 频道。",
                category="mcp",
                source="mcp",
                risk_level="low",
                requires_sandbox=False,
                network_policy="restricted",
                timeout_seconds=30,
                audit_level="standard",
                idempotent=True,
                input_schema={
                    "type": "object",
                    "properties": {
                        "types": {"type": "string"},
                        "limit": {"type": "integer", "default": 100},
                    },
                },
                mcp_server="slack",
                mcp_method="list_channels",
            ),
            ToolMetadata(
                name="slack.get_thread",
                description="读取 Slack thread 和回复。",
                category="mcp",
                source="mcp",
                risk_level="low",
                requires_sandbox=False,
                network_policy="restricted",
                timeout_seconds=30,
                audit_level="standard",
                idempotent=True,
                input_schema={
                    "type": "object",
                    "properties": {
                        "channel": {"type": "string"},
                        "thread_ts": {"type": "string"},
                    },
                    "required": ["channel", "thread_ts"],
                },
                mcp_server="slack",
                mcp_method="get_thread",
            ),
            ToolMetadata(
                name="slack.post_message",
                description="向 Slack 频道或用户发送消息。",
                category="mcp",
                source="mcp",
                risk_level="high",
                requires_sandbox=False,
                network_policy="restricted",
                timeout_seconds=30,
                audit_level="critical",
                idempotent=False,
                input_schema={
                    "type": "object",
                    "properties": {
                        "channel": {"type": "string"},
                        "text": {"type": "string"},
                        "thread_ts": {"type": "string"},
                        "idempotency_key": {"type": "string"},
                    },
                    "required": ["channel", "text", "idempotency_key"],
                },
                mcp_server="slack",
                mcp_method="post_message",
            ),
            ToolMetadata(
                name="slack.add_reaction",
                description="给 Slack 消息添加 emoji reaction。",
                category="mcp",
                source="mcp",
                risk_level="high",
                requires_sandbox=False,
                network_policy="restricted",
                timeout_seconds=30,
                audit_level="critical",
                idempotent=False,
                input_schema={
                    "type": "object",
                    "properties": {
                        "channel": {"type": "string"},
                        "timestamp": {"type": "string"},
                        "name": {"type": "string"},
                        "idempotency_key": {"type": "string"},
                    },
                    "required": ["channel", "timestamp", "name", "idempotency_key"],
                },
                mcp_server="slack",
                mcp_method="add_reaction",
            ),
            ToolMetadata(
                name="notion.search_pages",
                description="搜索 Notion 页面和数据库。",
                category="mcp",
                source="mcp",
                risk_level="low",
                requires_sandbox=False,
                network_policy="restricted",
                timeout_seconds=30,
                audit_level="standard",
                idempotent=True,
                input_schema={
                    "type": "object",
                    "properties": {
                        "query": {"type": "string"},
                        "limit": {"type": "integer", "default": 10},
                    },
                    "required": ["query"],
                },
                mcp_server="notion",
                mcp_method="search_pages",
            ),
            ToolMetadata(
                name="notion.get_page",
                description="读取 Notion 页面和子 block。",
                category="mcp",
                source="mcp",
                risk_level="low",
                requires_sandbox=False,
                network_policy="restricted",
                timeout_seconds=30,
                audit_level="standard",
                idempotent=True,
                input_schema={
                    "type": "object",
                    "properties": {
                        "page_id": {"type": "string"},
                        "include_blocks": {"type": "boolean", "default": True},
                        "limit": {"type": "integer", "default": 20},
                    },
                    "required": ["page_id"],
                },
                mcp_server="notion",
                mcp_method="get_page",
            ),
            ToolMetadata(
                name="notion.query_database",
                description="查询 Notion 数据库。",
                category="mcp",
                source="mcp",
                risk_level="low",
                requires_sandbox=False,
                network_policy="restricted",
                timeout_seconds=30,
                audit_level="standard",
                idempotent=True,
                input_schema={
                    "type": "object",
                    "properties": {
                        "database_id": {"type": "string"},
                        "filter": {"type": "object"},
                        "sorts": {"type": "array", "items": {"type": "object"}},
                        "limit": {"type": "integer", "default": 20},
                    },
                    "required": ["database_id"],
                },
                mcp_server="notion",
                mcp_method="query_database",
            ),
            ToolMetadata(
                name="notion.append_block",
                description="向 Notion block 追加段落。",
                category="mcp",
                source="mcp",
                risk_level="high",
                requires_sandbox=False,
                network_policy="restricted",
                timeout_seconds=30,
                audit_level="critical",
                idempotent=False,
                input_schema={
                    "type": "object",
                    "properties": {
                        "parent_block_id": {"type": "string"},
                        "text": {"type": "string"},
                        "idempotency_key": {"type": "string"},
                    },
                    "required": ["parent_block_id", "text", "idempotency_key"],
                },
                mcp_server="notion",
                mcp_method="append_block",
            ),
            ToolMetadata(
                name="linear.list_issues",
                description="列出 Linear Issue。",
                category="mcp",
                source="mcp",
                risk_level="low",
                requires_sandbox=False,
                network_policy="restricted",
                timeout_seconds=30,
                audit_level="standard",
                idempotent=True,
                input_schema={
                    "type": "object",
                    "properties": {
                        "team_key": {"type": "string"},
                        "query": {"type": "string"},
                        "state": {"type": "string"},
                        "limit": {"type": "integer", "default": 20},
                    },
                },
                mcp_server="linear",
                mcp_method="list_issues",
            ),
            ToolMetadata(
                name="linear.get_issue",
                description="读取 Linear Issue 和评论。",
                category="mcp",
                source="mcp",
                risk_level="low",
                requires_sandbox=False,
                network_policy="restricted",
                timeout_seconds=30,
                audit_level="standard",
                idempotent=True,
                input_schema={
                    "type": "object",
                    "properties": {
                        "issue_id": {"type": "string"},
                        "include_comments": {"type": "boolean", "default": True},
                    },
                    "required": ["issue_id"],
                },
                mcp_server="linear",
                mcp_method="get_issue",
            ),
            ToolMetadata(
                name="linear.create_issue",
                description="创建 Linear Issue。",
                category="mcp",
                source="mcp",
                risk_level="high",
                requires_sandbox=False,
                network_policy="restricted",
                timeout_seconds=30,
                audit_level="critical",
                idempotent=False,
                input_schema={
                    "type": "object",
                    "properties": {
                        "team_id": {"type": "string"},
                        "title": {"type": "string"},
                        "description": {"type": "string"},
                        "priority": {"type": "integer"},
                        "idempotency_key": {"type": "string"},
                    },
                    "required": ["team_id", "title", "idempotency_key"],
                },
                mcp_server="linear",
                mcp_method="create_issue",
            ),
            ToolMetadata(
                name="linear.create_comment",
                description="创建 Linear Issue 评论。",
                category="mcp",
                source="mcp",
                risk_level="high",
                requires_sandbox=False,
                network_policy="restricted",
                timeout_seconds=30,
                audit_level="critical",
                idempotent=False,
                input_schema={
                    "type": "object",
                    "properties": {
                        "issue_id": {"type": "string"},
                        "body": {"type": "string"},
                        "idempotency_key": {"type": "string"},
                    },
                    "required": ["issue_id", "body", "idempotency_key"],
                },
                mcp_server="linear",
                mcp_method="create_comment",
            ),
            ToolMetadata(
                name="code_interpreter.run_python",
                description="在 Agent 沙箱内运行受限 Python 代码。",
                category="mcp",
                source="mcp",
                risk_level="high",
                requires_sandbox=True,
                network_policy="none",
                timeout_seconds=60,
                audit_level="critical",
                idempotent=False,
                input_schema={
                    "type": "object",
                    "properties": {
                        "code": {"type": "string"},
                        "stdin": {"type": "string"},
                        "files": {"type": "array", "items": {"type": "object"}},
                        "timeout_seconds": {"type": "integer", "default": 30},
                        "idempotency_key": {"type": "string"},
                    },
                    "required": ["code", "idempotency_key"],
                },
                mcp_server="code-interpreter",
                mcp_method="run_python",
            ),
            ToolMetadata(
                name="code_interpreter.install_package",
                description="在 Agent 沙箱内安装 Python package。",
                category="mcp",
                source="mcp",
                risk_level="high",
                requires_sandbox=True,
                network_policy="restricted",
                timeout_seconds=60,
                audit_level="critical",
                idempotent=False,
                input_schema={
                    "type": "object",
                    "properties": {
                        "package": {"type": "string"},
                        "version": {"type": "string"},
                        "timeout_seconds": {"type": "integer", "default": 30},
                        "idempotency_key": {"type": "string"},
                    },
                    "required": ["package", "idempotency_key"],
                },
                mcp_server="code-interpreter",
                mcp_method="install_package",
            ),
            ToolMetadata(
                name="sandbox.read_file",
                description="读取沙箱工作区内文件。",
                category="mcp",
                source="mcp",
                risk_level="medium",
                requires_sandbox=True,
                network_policy="none",
                timeout_seconds=10,
                audit_level="elevated",
                idempotent=True,
                input_schema={
                    "type": "object",
                    "properties": {
                        "path": {"type": "string"},
                        "max_bytes": {"type": "integer", "default": 1000000},
                    },
                    "required": ["path"],
                },
                mcp_server="sandbox",
                mcp_method="read_file",
            ),
            ToolMetadata(
                name="sandbox.list_files",
                description="列出沙箱工作区内目录。",
                category="mcp",
                source="mcp",
                risk_level="medium",
                requires_sandbox=True,
                network_policy="none",
                timeout_seconds=10,
                audit_level="elevated",
                idempotent=True,
                input_schema={
                    "type": "object",
                    "properties": {
                        "path": {"type": "string", "default": "."},
                        "pattern": {"type": "string", "default": "*"},
                        "max_entries": {"type": "integer", "default": 200},
                    },
                },
                mcp_server="sandbox",
                mcp_method="list_files",
            ),
            ToolMetadata(
                name="sandbox.write_file",
                description="写入沙箱工作区内文件。",
                category="mcp",
                source="mcp",
                risk_level="high",
                requires_sandbox=True,
                network_policy="none",
                timeout_seconds=30,
                audit_level="critical",
                idempotent=False,
                input_schema={
                    "type": "object",
                    "properties": {
                        "path": {"type": "string"},
                        "content": {"type": "string"},
                        "encoding": {"type": "string", "default": "utf-8"},
                        "idempotency_key": {"type": "string"},
                    },
                    "required": ["path", "content", "idempotency_key"],
                },
                mcp_server="sandbox",
                mcp_method="write_file",
            ),
            ToolMetadata(
                name="sandbox.delete_file",
                description="删除沙箱工作区内文件。",
                category="mcp",
                source="mcp",
                risk_level="high",
                requires_sandbox=True,
                network_policy="none",
                timeout_seconds=30,
                audit_level="critical",
                idempotent=False,
                input_schema={
                    "type": "object",
                    "properties": {
                        "path": {"type": "string"},
                        "idempotency_key": {"type": "string"},
                    },
                    "required": ["path", "idempotency_key"],
                },
                mcp_server="sandbox",
                mcp_method="delete_file",
            ),
        ]
        return cls(tools={tool.name: tool for tool in tools})

    def list_tools(self) -> list[ToolMetadata]:
        return list(self.tools.values())
